from dataclasses import dataclass


@dataclass
class PatientRecord:
    """Stores basic patient registration details matching the portal."""
    patient_id: str        # e.g., "P-001", used as Firestore document ID
    full_name: str
    contact_number: str
    email_address: str     # unique
    date_of_birth: str     # ISO format "YYYY-MM-DD"


@dataclass
class DoctorProfile:
    """Stores doctor information for appointment scheduling."""
    doctor_id: str         # e.g., "12345", used as Firestore document ID
    doctor_name: str
    specialization: str


@dataclass
class AppointmentSlot:
    """Stores the specific date/time availability grid and appointment bookings."""
    slot_id: str           # Auto-generated by Firestore, used as document ID
    doctor_id: str         # References DoctorProfile
    patient_id: str = None # References PatientRecord (nullable)
    appointment_date: str = None  # ISO format "YYYY-MM-DD"
    day_of_week: str = ""         # e.g., "Monday"
    start_time: str = ""          # e.g., "09:00"
    end_time: str = ""            # e.g., "10:00"
    status: str = "Available"     # "Available" or "Booked"
